### ISSUE TITLE
Master branch tests failed.

### ISSUE THREAD

**Issue by lzbj** [openwhisk/openwhisk-wskdeploy#104]
Master branch tests failed, we need to fix it according to latest codes updates.

**Comment by rabbah** [comment]
It's really bad practice to merge code that breaks master.

**Comment by lzbj** [comment]
Ok, thank you for kind remind @rabbah , I'll take care next time and try fix it ASAP.

**Comment by rabbah** [comment]
Great! Thank you. Practicing good habits makes us all better.

**Comment by lzbj** [comment]
Close as fixed.
