### ISSUE TITLE
Generate template package using "init" or "generate" command

### ISSUE THREAD

**Issue by paulcastro** [openwhisk/openwhisk-wskdeploy#106]
It would be useful to have a `wskdeploy generate <package-name>` or `wskdeploy init <package-name>` , which could prompt the user for basic information about a package and generate a starter manifest.yaml as well as a starter directory structure (e.g. a `src` directory).  It could also generate a starter `deployment.yaml-template` file.  That way, a developer can use `wskdeploy` almost exclusively from the start of development to deploy their OpenWhisk assets.

**Comment by lionelvillard** [comment]
The `init` command should only create the manifest and a starter directory structure. Another command should be used for creating deployment. Eventually the `init` command could prompt the user to run the `add deployment` command after `init`.

The directory structure after `init` looks like this one:

    |- actions 
    |- feeds
    manifest.yaml

**Comment by lzbj** [comment]
close as pr merged.
