### ISSUE TITLE
Error while fetching gopkg.in/yaml.v2

### ISSUE THREAD

**Issue by lionelvillard** [openwhisk/openwhisk-wskdeploy#111]
when using newer git version, go get gopkg.in/yaml.v2 fails:

    Cloning into '/Users/villardl/Projects/whisk/whiskpm/src/gopkg.in/yaml.v2'... 
    error: RPC failed; HTTP 301 curl 22 The requested URL returned error: 301 
    fatal: The remote end hung up unexpectedly 

this is caused by git not forwarding redirect by default anymore. One fix is configure git to follow redirect for gopkg.in:

     git config --global http.https://gopkg.in.followRedirects true

maybe the readme should be updated as I except this is a common problem people will encounter.

**Comment by lzbj** [comment]
@lionelvillard ,pls help update the readme if you think it's better and submit pr. tks.
