### ISSUE TITLE
Look at creating compiled binary for non-developer users

### ISSUE THREAD

**Issue by mrutkows** [openwhisk/openwhisk-wskdeploy#117]
We would like to have a compiled version of the tool available for download by end users (not developers) so they do not need to install pre-reqs and build it themselves.

This issue would involve cross-compiling to allow running for Linux, Mac and Windows across processor architectures.

See: http://www.bite-code.com/2015/06/24/cross-compiling-go-on-mac-os-x/ as one article on how to do this.  Not sure if any improvements have been made in the last year or not (that is for owner to research).

**Comment by mrutkows** [comment]
Of course we would build to subdir of the project, as well as update the docs for "download".

**Comment by csantanapr** [comment]
We should leverage what we already did for the `wsk` to compile.
We use docker container that has the go env, have gradle script that compiles all binary architectures and platform build individual zips
Look at repo folder [tools/cli](https://github.com/openwhisk/openwhisk/tree/master/tools/cli) for details on docker file, script, and gradle.

**Comment by daisy-ycguo** [comment]
depends on #153

**Comment by lzbj** [comment]
@mrutkows @csantanapr , Yes, please help review pr https://github.com/openwhisk/openwhisk-wskdeploy/pull/181 thank you.

**Comment by daisy-ycguo** [comment]
Close as fixed.
