### ISSUE TITLE
Add build scripts to create cross platform binaries

### ISSUE THREAD

**Issue by paulcastro** [openwhisk/openwhisk-wskdeploy#153]
Need build scripts like the wsk CLI to create cross platform binaries.

**Comment by lzbj** [comment]
@paulcastro , Golang supports the cross compile well, for example, if user want to build for a windows platform, only type the command like "env GOOS=windows  GOARCH=386 go build", then the windows binary will be available. Probably we could provide a .bat file for a windows user?
For a linux/mac user, the current makefile is sufficient? what's your opinion?

**Comment by paulcastro** [comment]
Yes, the Makefile is good for most things.  For Travis and Jenkins builds,  the OW CLI builds the binaries inside a Docker container using a build script similar to the Makefile -- I'd like to use that method.

**Comment by daisy-ycguo** [comment]
We can follow the same technology that is used for `wsk` compiling and building. Look at [tools/cli](https://github.com/openwhisk/openwhisk/tree/master/tools/cli) for details on docker file, script, and gradle.

**Comment by lzbj** [comment]
Yes, totally agree with you, let's reuse the existing techs&scripts as carlos and matt comments.

**Comment by houshengbo** [comment]
@lzbj @daisy-ycguo What binaries do we expect to build? Based on the description here, I am sure that the wsk CLI is definitely one of them. Do we still expect anything else to be built, able to be described in the manifest?

**Comment by lzbj** [comment]
@houshengbo , I think we need to use gradle to build wskdeploy as did by wsk cli.

**Comment by paulcastro** [comment]
@houshengbo we don't need to build the entire wsk CLI -- I'd focus on building the wskdeploy binary.  That means building openwhisk/openwhisk-client-go and openwhisk/openwhisk-wskdploy.  I'd build for the most common architectures now (64 bit mac, linux and windows):

amd64 darwin  
amd64 windows
amd64 linux

**Comment by dubeejw** [comment]
Let me know if you have any questions as to how the WSK CLI build works.

**Comment by dubeejw** [comment]
I haven't looked through the project too much, but where will the built artifacts be placed? Is there a plan to publish them somewhere? I'm curious since this project looks like a possible candidate to become a plugin to the wsk CLI.

**Comment by mrutkows** [comment]
@dubeejw A tutorial would be great...

**Comment by lzbj** [comment]
@dubeejw , I submitted a pr to address this issue, could you please help review it, thanks.

I tested the pr and could get a binary under the bin folder. Also the .zip package is also under bin folder. The command is ./gradlew distDocker or gradle distDocker.

@mrutkows , I could write a tutorial or we could update the README. What do you think?

**Comment by mrutkows** [comment]
@houshengbo this is the binary issue which we need as high priority as well; again use David as needed.

**Comment by mrutkows** [comment]
@dubeejw I think we want to clearly (initially) place them in a "/bin/download" dir and then link them from our README (nad perhaps create a dedicated README in that download dir.   We of course, are working a longer term plan to build them with the greater CLI (and some framework/sdk) that will take us until June time-frame.

**Comment by daisy-ycguo** [comment]
The scripts are merged. The folder `bin` has an empty READEME.md. There is a section about how to download binaries in the root README.md. I think we can add this section also to `bin/README.md`.

**Comment by paulcastro** [comment]
Merged
