### ISSUE TITLE
wskdeploy should support package level bindings.

### ISSUE THREAD

**Issue by lzbj** [openwhisk/openwhisk-wskdeploy#158]
Currently we need to support OpenWhisk 101 use cases, and some of the use case need a package level binding, for example, the data processing cloudant use case needs to binding the /whisk.system/cloudant package, so we need to support this use case.

@mrutkows @paulcastro @daisy-ycguo , are we already supported this use case, I searched the use case in the code and spec samples, and didn't find clear definition, did I miss something?

**Comment by paulcastro** [comment]
You did not miss anything. We don't have package binding support anywhere.

**Comment by lzbj** [comment]
ok, I'll investigate it.

**Comment by lzbj** [comment]
close this one, please refer to https://github.com/openwhisk/openwhisk-wskdeploy/issues/41
