### ISSUE TITLE
Proposal: Enable the travis support with openwhisk and add the structure for integration tests 

### ISSUE THREAD

**Issue by houshengbo** [openwhisk/openwhisk-wskdeploy#177]
In order to run integration tests against an openwhisk deployment, openwhisk-wskdeploy needs to enable travis support with core openwhisk installation. Currently this is missing in this project.

openwhisk-wskdeploy needs to have an integration tests folder containing all the integration use cases supported by OpenWhisk. These test cases should pass within the travis to assure the code quality. Currently there is no integration test available in this project.

As the first iteration, the supported integration test cases can start with an easy one: install a basic action and a basic package with manifest and deployment files, verify if they have been installed in openwhisk, remove them in openwhisk, and verify if they have been removed in openwhisk.

For further iterations, the integration test cases need to be documented as the basic features for wskdeploy to support.

**Comment by houshengbo** [comment]
@lzbj David, I have established the backbone for the integration tests running in Travis CI. I only added one integration test in the PR #199. I need you to add more integration tests into tests/src/integration.

**Comment by lzbj** [comment]
@houshengbo , got it, I'll take a look.

**Comment by lzbj** [comment]
@houshengbo ,it's finished, right, close it.
