### ISSUE TITLE
Proposal: Offer wskdeploy in terms of a zip package automatically

### ISSUE THREAD

**Issue by houshengbo** [openwhisk/openwhisk-wskdeploy#180]
For users of wskdeploy, they should only care about the binary to deploy openwhisk entities or components.

It would be great if wskdeploy is offered as a zip package containing all the necessary binary build in an automatic way, so that the user can directly download, unzip it and use it via the command ./wskdeploy ... .

A good approach is to enable travis github release to run the build and post the zip file automatically in a designated directory.

**Comment by mrutkows** [comment]
@houshengbo Please see issue: https://github.com/openwhisk/openwhisk-wskdeploy/issues/153
as David is already working on cross-platform binaries that will be offered from project README for download. If we have that, we perhaps do not need a ZIP file as there is only 1 binary.

**Comment by houshengbo** [comment]
@mrutkows I think I did not make this issue clear at the first time. I have modified the description and this issue is also part of the automation for our build.

**Comment by mrutkows** [comment]
@houshengbo assigning this to you... as Daniel @krook indicated this would be one of the priority issues for interconnect...

**Comment by mrutkows** [comment]
@houshengbo please use David as needed to help.

**Comment by mrutkows** [comment]
related to https://github.com/openwhisk/openwhisk-wskdeploy/issues/153

**Comment by houshengbo** [comment]
@mrutkows The binary generation and deployment are able to be done by travis ci, since @csantanapr has merge the PR after changing the api_key for openwhisk-wskdeploy repo. 
@lzbj What is the binary generation you are working on? Is it something similar to the travis deploy in this repo?
