### ISSUE TITLE
Update README about how to cross compile binary with latest update.

### ISSUE THREAD

**Issue by lzbj** [openwhisk/openwhisk-wskdeploy#197]
Mainly tell user how to use java/gradle/docker to get cross compiled binary.

**Comment by houshengbo** [comment]
@lzbj I was just thinking of opening a similar issue. It will be very handy if you update the doc accordingly.

**Comment by lzbj** [comment]
@houshengbo , sure, I'll update the gradle/docker part, I noticed you updated the travis integration with some cross compile and tag support, so feel free to comment or update if you want.
