### ISSUE TITLE
exec.Jar never defined: exec.Jar = base64.StdEncoding.EncodeToString([]byte(code))

### ISSUE THREAD

**Issue by houshengbo** [openwhisk/openwhisk-wskdeploy#227]
https://github.com/openwhisk/openwhisk-wskdeploy/commit/34bcfc6b2d46fe055b018a3931371b13682b3d1f
@lzbj The commit you did and merge has an issue.
exec.Jar = base64.StdEncoding.EncodeToString([]byte(code))
Jar is not available in exec, and Jar is never used anywhere. Please add tests to the changes you add. Otherwise we cannot secure the quality.
Thx.

**Comment by houshengbo** [comment]
@lzbj I have removed this line of code in my PR: https://github.com/openwhisk/openwhisk-wskdeploy/pull/199. Thanks to the integration test in it. Otherwise, I would not even know the error.

**Comment by lzbj** [comment]
tks, @houshengbo , please open an issue to openwhisk cli if you think it's a issue, the code is from go cli, it's not CI test.
