### ISSUE TITLE
Dockerfile is only able to build the binaries based on the packages in the github, not local packages.

### ISSUE THREAD

**Issue by houshengbo** [openwhisk/openwhisk-wskdeploy#228]
The reason for the current Dockerfile only able to build based on the packages in the github is that dockerfile physically pulls the code from openwhisk-client-go and openwhisk-wskdeploy each time we run it. No matter how much we change locally with the code, the docker build will not take effect, since the packages put under the go path are always the ones cloned from the github repo, not local changes.

Instead, we should  copy the packages from local code base into the designated directories under GOPATH, and build the binaries based on the local code.

**Comment by lzbj** [comment]
close as merged
