### ISSUE TITLE
Check if wskdeploy supports env. variables in manifest/deployment file

### ISSUE THREAD

**Issue by pritidesai** [openwhisk/openwhisk-wskdeploy#249]
Generally, while creating package binding, it takes hostname, credentials, etc. as input parameters. And ideally its best to set env. with such sensitive information instead of hardcoding in a yaml file. Do we have support for env. variables in manifest/deployment yaml file? Can we specify something like:

```
 inputs:
                username: $CLOUDANT_USERNAME
                password: $CLOUDANT_PASSWORD
```

@mrutkows @daisy-ycguo @houshengbo @paulcastro

**Comment by lionelvillard** [comment]
Yes env variables are supported.

**Comment by pritidesai** [comment]
Thanks @lionelvillard also found an explanation in specification file:

**Setting values using ($) dollar notation**

In the Deployment file, a parameter value may be set from the local execution environment by using the dollar ($) notation to denote names of local environment variables which supply the value to be inserted at execution time.

Syntax

`<parameter>: $<local environment variable name>`

Example

```
  ... inputs:
          userName: $DEFAULT_USERNAME
```
