### ISSUE TITLE
Add a simple UI through web browser then CLi.

### ISSUE THREAD

**Issue by lzbj** [openwhisk/openwhisk-wskdeploy#68]
We could add a simple UI through web browser if user don't want to bother with Cli, it's perhaps more intuitive, we could wrap up go cli with a web server, and some basic HTML template.

**Comment by daisy-ycguo** [comment]
We may need to take a look at how to integrate wskdeploy into OpenWhisk management UI in Bluemix.

OpenWhisk editor in Bluemix supports two kind of interfaces: Web UI and the CLI.
- CLI: Can `wskdeploy` be a part of wsk cli ? We may consider to use `wsk deploy` to invoke the real go program `wskdeploy`.
- Web UI: The current web UI is not able to manage packages. We may add a section under `manage` menu called `Package`. We can allow users to import/delete packages. When importing a package, a URL is specified or a local zip/jar/tar file is specified and uploaded.

**Comment by lzbj** [comment]
@daisy-ycguo ， please open a issue if you think we should integrate with blume mix cli, I'll close this one.
