### ISSUE TITLE
Support 'wskdeploy undeploy'

### ISSUE THREAD

**Issue by daisy-ycguo** [openwhisk/openwhisk-wskdeploy#93]
The goal would be to read a manifest file, then remove all entities currently deployed in OpenWhisk.

**Comment by lzbj** [comment]
Good feature.

**Comment by paulcastro** [comment]
Do we want to think of having a "verify" feature as part of this (or as a separate issue?).  Verify would read the manifest and deployment files, then check to see what is already installed in OpenWhisk. Verify is probably useful on its own, but I'm thinking that it can be used during deploy or undeploy to update just what has changed.

**Comment by lzbj** [comment]
Good point, is it like a diff tool to help users know the difference between existing entities and entities defined in deployment and manifest? if that's the case, my personnel view is we add it as a separate cmd, to help user determine next step(deploy or undeploy).

**Comment by lzbj** [comment]
@paulcastro , I opened another issue for this, I think it's a step before we implement undeploy.

**Comment by lzbj** [comment]
Close as pr merged.
