### ISSUE TITLE
[WIP] Add deploy cmd. 

### ISSUE THREAD

**Issue by lzbj** [openwhisk/openwhisk-wskdeploy#99]
Currently the deploy were a default behavior under root command, and the manifest and deployment flag are global flags, we need to separate deploy/undeploy and corresponding
flags under each command. Add this issue to separate the refactor progress.

**Comment by paulcastro** [comment]
Let's keep the deploy command in root for now.  I remember now that `wskdeploy deploy` is awkward.  however, we should definitely have an undeploy command `wskdeploy undeploy`
